In [3]:
import tensorflow as tf
from tensorflow import keras 

In [9]:
mnist= keras.datasets.mnist

(x_train, y_train), (x_test, y_test)= mnist.load_data() #the function returns to tuples

#pictures in this category range from 0-255... 256 values per RGB
#to normalize those values, let's divide them by 255.0

x_train, x_test = x_train/255.0, x_test/255.0

model= keras.models.Sequential([
                               keras.layers.Flatten(input_shape=(28,28)),
                               keras.layers.Dense(128, activation="relu"),
                               keras.layers.Dense(10),
                               ])

print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [16]:
loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optim= keras.optimizers.Adam(learning_rate=0.001)
metric=["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metric)

#set the batch size and the number of epochs

batch_size=32
epochs=25

model.fit(x_train, y_train, batch_size=batch_size, epochs= epochs, shuffle=True, verbose=2)

Epoch 1/25
1875/1875 - 5s - loss: 0.1278 - accuracy: 0.9635 - 5s/epoch - 2ms/step
Epoch 2/25
1875/1875 - 4s - loss: 0.1267 - accuracy: 0.9635 - 4s/epoch - 2ms/step
Epoch 3/25
1875/1875 - 4s - loss: 0.1255 - accuracy: 0.9634 - 4s/epoch - 2ms/step
Epoch 4/25
1875/1875 - 4s - loss: 0.1245 - accuracy: 0.9640 - 4s/epoch - 2ms/step
Epoch 5/25
1875/1875 - 4s - loss: 0.1241 - accuracy: 0.9641 - 4s/epoch - 2ms/step
Epoch 6/25
1875/1875 - 4s - loss: 0.1231 - accuracy: 0.9642 - 4s/epoch - 2ms/step
Epoch 7/25
1875/1875 - 4s - loss: 0.1223 - accuracy: 0.9646 - 4s/epoch - 2ms/step
Epoch 8/25
1875/1875 - 4s - loss: 0.1215 - accuracy: 0.9643 - 4s/epoch - 2ms/step
Epoch 9/25
1875/1875 - 4s - loss: 0.1203 - accuracy: 0.9652 - 4s/epoch - 2ms/step
Epoch 10/25
1875/1875 - 4s - loss: 0.1198 - accuracy: 0.9652 - 4s/epoch - 2ms/step
Epoch 11/25
1875/1875 - 4s - loss: 0.1191 - accuracy: 0.9654 - 4s/epoch - 2ms/step
Epoch 12/25
1875/1875 - 4s - loss: 0.1185 - accuracy: 0.9655 - 4s/epoch - 2ms/step
Epoch 13/25
1

**evaluate the model**

In [17]:
model.evaluate(x_test, y_test, batch_size=batch_size, verbose=2)

313/313 - 1s - loss: 0.2624 - accuracy: 0.9506 - 565ms/epoch - 2ms/step


[0.26243868470191956, 0.9506000280380249]

**predictions from the model**

In [18]:
import numpy as np  #insert this statement in the 1st cell itself

probability_model= keras.models.Sequential([
                                            model,
                                            keras.layers.Softmax()
])

predictions= probability_model(x_test)
pred0= predictions[0]
print(pred0)

label0= np.argmax(pred0)

print(label0)

tf.Tensor(
[2.9394513e-20 3.5001633e-06 6.3850224e-05 1.2203665e-04 1.0627135e-17
 3.7094921e-08 6.2748312e-20 9.9981052e-01 1.8413729e-18 5.7933000e-18], shape=(10,), dtype=float32)
7


**Predictions + Softmax**

In [19]:
predictions= model.predict(x_test, batch_size=batch_size)
predictions= tf.nn.softmax(predictions) 
pred0= predictions[0]
print(pred0)

label0= np.argmax(pred0)

print(label0)

pred05s= predictions[0:5]
print(pred05s.shape)
label05s= np.argmax(pred05s, axis=1)

print(label05s)



tf.Tensor(
[2.9394513e-20 3.5001633e-06 6.3850224e-05 1.2203665e-04 1.0627135e-17
 3.7094921e-08 6.2748312e-20 9.9981052e-01 1.8413729e-18 5.7933000e-18], shape=(10,), dtype=float32)
7
(5, 10)
[7 2 1 0 4]
